baseURL = 'https://livefitt.net/'
languageCode = 'en-us'
title = 'LiveFitt'
theme = 'BlogRa'

[params]
    description     = "The Ultimate Tech Blogging Theme"
    contactEmail    = "your-email@domain.com"
    footer          = ""
    googleSearch    = ""
    googleAnalytics = ""      # Google Analytics v4
    adsense         = "ca-pub-4531697702826116"
    math            = false   # best to enable this in the front matter of a page
    mermaid         = false   # best to enable this in the front matter of a page

    # Social Media Params
    facebook   = ""
    twitter    = ""
    youtube    = ""
    instagram  = ""
    github     = ""
    pinterest  = ""
    linkedin   = ""

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Posts"
	url = "/posts/"
        weight = 2
